apiVersion: v1
kind: Service
metadata:
  name: terrakube-api-ts-proxy
  namespace: tailscale
spec:
  selector:
    tailscale.com/parent-resource: terrakube-api
    tailscale.com/parent-resource-type: ingress
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
