apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terrakube
  namespace: argocd
spec:
  project: infra
  sources:
    - path: infra/terrakube
      repoURL: https://github.com/code4romania/code4ro-k8s.git
      targetRevision: HEAD
      ref: myRepo
    - repoURL: https://terrakube-io.github.io/terrakube-helm-chart
      targetRevision: 4.6.2
      chart: terrakube
      helm:
        valueFiles:
          - $myRepo/infra/terrakube/helm-chart-values/values.yaml
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: terrakube-api
      jsonPointers:
        - /spec/template/spec/hostAliases
  destination:
    namespace: terrakube
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
